version: 0.2
phases:
  install:
    commands:
      - python -m pip install -r requirements.txt
  build:
    commands:
      - cdk synth
      - cdk deploy --require-approval never
artifacts:
  files:
    - '**/*'